require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  StyleGuideBaseURL: https://rubystyle.guide
  NewCops: enable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Metrics/AbcSize:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/ClassAndModuleChildren:
  Exclude:
    - 'spec/**/*'
