AllCops:
  TargetRubyVersion: 2.5
  StyleGuideBaseURL: https://rubystyle.guide
  NewCops: enable

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
