version: '3'
services:
  pronto:
    image: ghcr.io/heromo/pronto-action:v1.66.0
    volumes:
      - .:/app
    entrypoint: ["bundle", "exec", "pronto"]
    command: run /app --commit main -r rubocop

# pronto-action https://github.com/marketplace/actions/pronto-action

# Run the following command to run pronto locally
# > docker-compose -f docker-compose-pronto.yml run --rm pronto
# > docker-compose -f docker-compose-pronto.yml run --rm pronto run /app -c main -r rubocop --staged
