name: Pronto
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  pronto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        fetch-depth: '0'
      - uses: HeRoMo/pronto-action@v1.9.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit: origin/main
