name: Pronto
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  pronto:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      pull_request: write
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: HeRoMo/pronto-action@v1.19.0
        with:
          commit: origin/${{ github.base_ref }}
